// flow-typed signature: b2b08f5444981be934635daf987b559d
// flow-typed version: <<STUB>>/iban_v^0.0.10/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'iban'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'iban' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'iban/demo/bower_components/bootstrap/dist/js/bootstrap' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/bootstrap/dist/js/bootstrap.min' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/bootstrap/dist/js/npm' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/bootstrap/grunt/bs-commonjs-generator' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/bootstrap/grunt/bs-glyphicons-data-generator' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/bootstrap/grunt/bs-lessdoc-parser' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/bootstrap/grunt/bs-raw-files-generator' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/bootstrap/grunt/change-version' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/bootstrap/Gruntfile' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/bootstrap/js/affix' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/bootstrap/js/alert' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/bootstrap/js/button' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/bootstrap/js/carousel' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/bootstrap/js/collapse' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/bootstrap/js/dropdown' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/bootstrap/js/modal' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/bootstrap/js/popover' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/bootstrap/js/scrollspy' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/bootstrap/js/tab' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/bootstrap/js/tooltip' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/bootstrap/js/transition' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/chai/chai' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/chai/karma.conf' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/chai/karma.sauce' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/chai/sauce.browsers' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/iban/iban' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/jquery/dist/core' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/jquery/dist/jquery' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/jquery/dist/jquery.min' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/jquery/dist/jquery.slim' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/jquery/dist/jquery.slim.min' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/jquery/external/sizzle/dist/sizzle' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/jquery/external/sizzle/dist/sizzle.min' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/jquery/src/ajax' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/jquery/src/ajax/jsonp' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/jquery/src/ajax/load' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/jquery/src/ajax/parseXML' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/jquery/src/ajax/script' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/jquery/src/ajax/var/location' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/jquery/src/ajax/var/nonce' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/jquery/src/ajax/var/rquery' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/jquery/src/ajax/xhr' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/jquery/src/attributes' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/jquery/src/attributes/attr' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/jquery/src/attributes/classes' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/jquery/src/attributes/prop' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/jquery/src/attributes/support' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/jquery/src/attributes/val' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/jquery/src/callbacks' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/jquery/src/core' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/jquery/src/core/access' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/jquery/src/core/DOMEval' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/jquery/src/core/init' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/jquery/src/core/nodeName' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/jquery/src/core/parseHTML' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/jquery/src/core/ready-no-deferred' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/jquery/src/core/ready' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/jquery/src/core/readyException' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/jquery/src/core/stripAndCollapse' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/jquery/src/core/support' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/jquery/src/core/var/rsingleTag' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/jquery/src/css' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/jquery/src/css/addGetHookIf' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/jquery/src/css/adjustCSS' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/jquery/src/css/curCSS' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/jquery/src/css/hiddenVisibleSelectors' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/jquery/src/css/showHide' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/jquery/src/css/support' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/jquery/src/css/var/cssExpand' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/jquery/src/css/var/getStyles' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/jquery/src/css/var/isHiddenWithinTree' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/jquery/src/css/var/rmargin' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/jquery/src/css/var/rnumnonpx' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/jquery/src/css/var/swap' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/jquery/src/data' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/jquery/src/data/Data' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/jquery/src/data/var/acceptData' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/jquery/src/data/var/dataPriv' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/jquery/src/data/var/dataUser' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/jquery/src/deferred' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/jquery/src/deferred/exceptionHook' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/jquery/src/deprecated' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/jquery/src/dimensions' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/jquery/src/effects' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/jquery/src/effects/animatedSelector' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/jquery/src/effects/Tween' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/jquery/src/event' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/jquery/src/event/ajax' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/jquery/src/event/alias' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/jquery/src/event/focusin' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/jquery/src/event/support' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/jquery/src/event/trigger' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/jquery/src/exports/amd' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/jquery/src/exports/global' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/jquery/src/jquery' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/jquery/src/manipulation' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/jquery/src/manipulation/_evalUrl' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/jquery/src/manipulation/buildFragment' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/jquery/src/manipulation/getAll' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/jquery/src/manipulation/setGlobalEval' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/jquery/src/manipulation/support' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/jquery/src/manipulation/var/rcheckableType' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/jquery/src/manipulation/var/rscriptType' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/jquery/src/manipulation/var/rtagName' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/jquery/src/manipulation/wrapMap' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/jquery/src/offset' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/jquery/src/queue' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/jquery/src/queue/delay' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/jquery/src/selector-native' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/jquery/src/selector-sizzle' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/jquery/src/selector' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/jquery/src/serialize' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/jquery/src/traversing' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/jquery/src/traversing/findFilter' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/jquery/src/traversing/var/dir' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/jquery/src/traversing/var/rneedsContext' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/jquery/src/traversing/var/siblings' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/jquery/src/var/arr' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/jquery/src/var/class2type' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/jquery/src/var/concat' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/jquery/src/var/document' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/jquery/src/var/documentElement' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/jquery/src/var/fnToString' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/jquery/src/var/getProto' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/jquery/src/var/hasOwn' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/jquery/src/var/indexOf' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/jquery/src/var/ObjectFunctionString' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/jquery/src/var/pnum' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/jquery/src/var/push' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/jquery/src/var/rcssNum' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/jquery/src/var/rnothtmlwhite' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/jquery/src/var/slice' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/jquery/src/var/support' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/jquery/src/var/toString' {
  declare module.exports: any;
}

declare module 'iban/demo/bower_components/jquery/src/wrap' {
  declare module.exports: any;
}

declare module 'iban/demo/js/countries' {
  declare module.exports: any;
}

declare module 'iban/demo/js/demo' {
  declare module.exports: any;
}

declare module 'iban/demo/js/ie-emulation-modes-warning' {
  declare module.exports: any;
}

declare module 'iban/demo/js/ie10-viewport-bug-workaround' {
  declare module.exports: any;
}

declare module 'iban/iban' {
  declare module.exports: any;
}

declare module 'iban/test/ibanTest' {
  declare module.exports: any;
}

// Filename aliases
declare module 'iban/demo/bower_components/bootstrap/dist/js/bootstrap.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/bootstrap/dist/js/bootstrap'>;
}
declare module 'iban/demo/bower_components/bootstrap/dist/js/bootstrap.min.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/bootstrap/dist/js/bootstrap.min'>;
}
declare module 'iban/demo/bower_components/bootstrap/dist/js/npm.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/bootstrap/dist/js/npm'>;
}
declare module 'iban/demo/bower_components/bootstrap/grunt/bs-commonjs-generator.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/bootstrap/grunt/bs-commonjs-generator'>;
}
declare module 'iban/demo/bower_components/bootstrap/grunt/bs-glyphicons-data-generator.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/bootstrap/grunt/bs-glyphicons-data-generator'>;
}
declare module 'iban/demo/bower_components/bootstrap/grunt/bs-lessdoc-parser.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/bootstrap/grunt/bs-lessdoc-parser'>;
}
declare module 'iban/demo/bower_components/bootstrap/grunt/bs-raw-files-generator.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/bootstrap/grunt/bs-raw-files-generator'>;
}
declare module 'iban/demo/bower_components/bootstrap/grunt/change-version.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/bootstrap/grunt/change-version'>;
}
declare module 'iban/demo/bower_components/bootstrap/Gruntfile.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/bootstrap/Gruntfile'>;
}
declare module 'iban/demo/bower_components/bootstrap/js/affix.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/bootstrap/js/affix'>;
}
declare module 'iban/demo/bower_components/bootstrap/js/alert.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/bootstrap/js/alert'>;
}
declare module 'iban/demo/bower_components/bootstrap/js/button.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/bootstrap/js/button'>;
}
declare module 'iban/demo/bower_components/bootstrap/js/carousel.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/bootstrap/js/carousel'>;
}
declare module 'iban/demo/bower_components/bootstrap/js/collapse.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/bootstrap/js/collapse'>;
}
declare module 'iban/demo/bower_components/bootstrap/js/dropdown.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/bootstrap/js/dropdown'>;
}
declare module 'iban/demo/bower_components/bootstrap/js/modal.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/bootstrap/js/modal'>;
}
declare module 'iban/demo/bower_components/bootstrap/js/popover.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/bootstrap/js/popover'>;
}
declare module 'iban/demo/bower_components/bootstrap/js/scrollspy.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/bootstrap/js/scrollspy'>;
}
declare module 'iban/demo/bower_components/bootstrap/js/tab.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/bootstrap/js/tab'>;
}
declare module 'iban/demo/bower_components/bootstrap/js/tooltip.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/bootstrap/js/tooltip'>;
}
declare module 'iban/demo/bower_components/bootstrap/js/transition.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/bootstrap/js/transition'>;
}
declare module 'iban/demo/bower_components/chai/chai.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/chai/chai'>;
}
declare module 'iban/demo/bower_components/chai/karma.conf.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/chai/karma.conf'>;
}
declare module 'iban/demo/bower_components/chai/karma.sauce.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/chai/karma.sauce'>;
}
declare module 'iban/demo/bower_components/chai/sauce.browsers.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/chai/sauce.browsers'>;
}
declare module 'iban/demo/bower_components/iban/iban.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/iban/iban'>;
}
declare module 'iban/demo/bower_components/jquery/dist/core.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/jquery/dist/core'>;
}
declare module 'iban/demo/bower_components/jquery/dist/jquery.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/jquery/dist/jquery'>;
}
declare module 'iban/demo/bower_components/jquery/dist/jquery.min.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/jquery/dist/jquery.min'>;
}
declare module 'iban/demo/bower_components/jquery/dist/jquery.slim.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/jquery/dist/jquery.slim'>;
}
declare module 'iban/demo/bower_components/jquery/dist/jquery.slim.min.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/jquery/dist/jquery.slim.min'>;
}
declare module 'iban/demo/bower_components/jquery/external/sizzle/dist/sizzle.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/jquery/external/sizzle/dist/sizzle'>;
}
declare module 'iban/demo/bower_components/jquery/external/sizzle/dist/sizzle.min.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/jquery/external/sizzle/dist/sizzle.min'>;
}
declare module 'iban/demo/bower_components/jquery/src/ajax.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/jquery/src/ajax'>;
}
declare module 'iban/demo/bower_components/jquery/src/ajax/jsonp.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/jquery/src/ajax/jsonp'>;
}
declare module 'iban/demo/bower_components/jquery/src/ajax/load.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/jquery/src/ajax/load'>;
}
declare module 'iban/demo/bower_components/jquery/src/ajax/parseXML.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/jquery/src/ajax/parseXML'>;
}
declare module 'iban/demo/bower_components/jquery/src/ajax/script.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/jquery/src/ajax/script'>;
}
declare module 'iban/demo/bower_components/jquery/src/ajax/var/location.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/jquery/src/ajax/var/location'>;
}
declare module 'iban/demo/bower_components/jquery/src/ajax/var/nonce.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/jquery/src/ajax/var/nonce'>;
}
declare module 'iban/demo/bower_components/jquery/src/ajax/var/rquery.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/jquery/src/ajax/var/rquery'>;
}
declare module 'iban/demo/bower_components/jquery/src/ajax/xhr.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/jquery/src/ajax/xhr'>;
}
declare module 'iban/demo/bower_components/jquery/src/attributes.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/jquery/src/attributes'>;
}
declare module 'iban/demo/bower_components/jquery/src/attributes/attr.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/jquery/src/attributes/attr'>;
}
declare module 'iban/demo/bower_components/jquery/src/attributes/classes.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/jquery/src/attributes/classes'>;
}
declare module 'iban/demo/bower_components/jquery/src/attributes/prop.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/jquery/src/attributes/prop'>;
}
declare module 'iban/demo/bower_components/jquery/src/attributes/support.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/jquery/src/attributes/support'>;
}
declare module 'iban/demo/bower_components/jquery/src/attributes/val.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/jquery/src/attributes/val'>;
}
declare module 'iban/demo/bower_components/jquery/src/callbacks.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/jquery/src/callbacks'>;
}
declare module 'iban/demo/bower_components/jquery/src/core.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/jquery/src/core'>;
}
declare module 'iban/demo/bower_components/jquery/src/core/access.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/jquery/src/core/access'>;
}
declare module 'iban/demo/bower_components/jquery/src/core/DOMEval.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/jquery/src/core/DOMEval'>;
}
declare module 'iban/demo/bower_components/jquery/src/core/init.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/jquery/src/core/init'>;
}
declare module 'iban/demo/bower_components/jquery/src/core/nodeName.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/jquery/src/core/nodeName'>;
}
declare module 'iban/demo/bower_components/jquery/src/core/parseHTML.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/jquery/src/core/parseHTML'>;
}
declare module 'iban/demo/bower_components/jquery/src/core/ready-no-deferred.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/jquery/src/core/ready-no-deferred'>;
}
declare module 'iban/demo/bower_components/jquery/src/core/ready.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/jquery/src/core/ready'>;
}
declare module 'iban/demo/bower_components/jquery/src/core/readyException.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/jquery/src/core/readyException'>;
}
declare module 'iban/demo/bower_components/jquery/src/core/stripAndCollapse.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/jquery/src/core/stripAndCollapse'>;
}
declare module 'iban/demo/bower_components/jquery/src/core/support.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/jquery/src/core/support'>;
}
declare module 'iban/demo/bower_components/jquery/src/core/var/rsingleTag.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/jquery/src/core/var/rsingleTag'>;
}
declare module 'iban/demo/bower_components/jquery/src/css.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/jquery/src/css'>;
}
declare module 'iban/demo/bower_components/jquery/src/css/addGetHookIf.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/jquery/src/css/addGetHookIf'>;
}
declare module 'iban/demo/bower_components/jquery/src/css/adjustCSS.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/jquery/src/css/adjustCSS'>;
}
declare module 'iban/demo/bower_components/jquery/src/css/curCSS.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/jquery/src/css/curCSS'>;
}
declare module 'iban/demo/bower_components/jquery/src/css/hiddenVisibleSelectors.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/jquery/src/css/hiddenVisibleSelectors'>;
}
declare module 'iban/demo/bower_components/jquery/src/css/showHide.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/jquery/src/css/showHide'>;
}
declare module 'iban/demo/bower_components/jquery/src/css/support.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/jquery/src/css/support'>;
}
declare module 'iban/demo/bower_components/jquery/src/css/var/cssExpand.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/jquery/src/css/var/cssExpand'>;
}
declare module 'iban/demo/bower_components/jquery/src/css/var/getStyles.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/jquery/src/css/var/getStyles'>;
}
declare module 'iban/demo/bower_components/jquery/src/css/var/isHiddenWithinTree.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/jquery/src/css/var/isHiddenWithinTree'>;
}
declare module 'iban/demo/bower_components/jquery/src/css/var/rmargin.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/jquery/src/css/var/rmargin'>;
}
declare module 'iban/demo/bower_components/jquery/src/css/var/rnumnonpx.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/jquery/src/css/var/rnumnonpx'>;
}
declare module 'iban/demo/bower_components/jquery/src/css/var/swap.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/jquery/src/css/var/swap'>;
}
declare module 'iban/demo/bower_components/jquery/src/data.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/jquery/src/data'>;
}
declare module 'iban/demo/bower_components/jquery/src/data/Data.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/jquery/src/data/Data'>;
}
declare module 'iban/demo/bower_components/jquery/src/data/var/acceptData.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/jquery/src/data/var/acceptData'>;
}
declare module 'iban/demo/bower_components/jquery/src/data/var/dataPriv.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/jquery/src/data/var/dataPriv'>;
}
declare module 'iban/demo/bower_components/jquery/src/data/var/dataUser.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/jquery/src/data/var/dataUser'>;
}
declare module 'iban/demo/bower_components/jquery/src/deferred.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/jquery/src/deferred'>;
}
declare module 'iban/demo/bower_components/jquery/src/deferred/exceptionHook.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/jquery/src/deferred/exceptionHook'>;
}
declare module 'iban/demo/bower_components/jquery/src/deprecated.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/jquery/src/deprecated'>;
}
declare module 'iban/demo/bower_components/jquery/src/dimensions.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/jquery/src/dimensions'>;
}
declare module 'iban/demo/bower_components/jquery/src/effects.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/jquery/src/effects'>;
}
declare module 'iban/demo/bower_components/jquery/src/effects/animatedSelector.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/jquery/src/effects/animatedSelector'>;
}
declare module 'iban/demo/bower_components/jquery/src/effects/Tween.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/jquery/src/effects/Tween'>;
}
declare module 'iban/demo/bower_components/jquery/src/event.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/jquery/src/event'>;
}
declare module 'iban/demo/bower_components/jquery/src/event/ajax.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/jquery/src/event/ajax'>;
}
declare module 'iban/demo/bower_components/jquery/src/event/alias.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/jquery/src/event/alias'>;
}
declare module 'iban/demo/bower_components/jquery/src/event/focusin.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/jquery/src/event/focusin'>;
}
declare module 'iban/demo/bower_components/jquery/src/event/support.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/jquery/src/event/support'>;
}
declare module 'iban/demo/bower_components/jquery/src/event/trigger.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/jquery/src/event/trigger'>;
}
declare module 'iban/demo/bower_components/jquery/src/exports/amd.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/jquery/src/exports/amd'>;
}
declare module 'iban/demo/bower_components/jquery/src/exports/global.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/jquery/src/exports/global'>;
}
declare module 'iban/demo/bower_components/jquery/src/jquery.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/jquery/src/jquery'>;
}
declare module 'iban/demo/bower_components/jquery/src/manipulation.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/jquery/src/manipulation'>;
}
declare module 'iban/demo/bower_components/jquery/src/manipulation/_evalUrl.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/jquery/src/manipulation/_evalUrl'>;
}
declare module 'iban/demo/bower_components/jquery/src/manipulation/buildFragment.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/jquery/src/manipulation/buildFragment'>;
}
declare module 'iban/demo/bower_components/jquery/src/manipulation/getAll.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/jquery/src/manipulation/getAll'>;
}
declare module 'iban/demo/bower_components/jquery/src/manipulation/setGlobalEval.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/jquery/src/manipulation/setGlobalEval'>;
}
declare module 'iban/demo/bower_components/jquery/src/manipulation/support.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/jquery/src/manipulation/support'>;
}
declare module 'iban/demo/bower_components/jquery/src/manipulation/var/rcheckableType.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/jquery/src/manipulation/var/rcheckableType'>;
}
declare module 'iban/demo/bower_components/jquery/src/manipulation/var/rscriptType.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/jquery/src/manipulation/var/rscriptType'>;
}
declare module 'iban/demo/bower_components/jquery/src/manipulation/var/rtagName.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/jquery/src/manipulation/var/rtagName'>;
}
declare module 'iban/demo/bower_components/jquery/src/manipulation/wrapMap.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/jquery/src/manipulation/wrapMap'>;
}
declare module 'iban/demo/bower_components/jquery/src/offset.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/jquery/src/offset'>;
}
declare module 'iban/demo/bower_components/jquery/src/queue.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/jquery/src/queue'>;
}
declare module 'iban/demo/bower_components/jquery/src/queue/delay.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/jquery/src/queue/delay'>;
}
declare module 'iban/demo/bower_components/jquery/src/selector-native.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/jquery/src/selector-native'>;
}
declare module 'iban/demo/bower_components/jquery/src/selector-sizzle.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/jquery/src/selector-sizzle'>;
}
declare module 'iban/demo/bower_components/jquery/src/selector.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/jquery/src/selector'>;
}
declare module 'iban/demo/bower_components/jquery/src/serialize.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/jquery/src/serialize'>;
}
declare module 'iban/demo/bower_components/jquery/src/traversing.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/jquery/src/traversing'>;
}
declare module 'iban/demo/bower_components/jquery/src/traversing/findFilter.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/jquery/src/traversing/findFilter'>;
}
declare module 'iban/demo/bower_components/jquery/src/traversing/var/dir.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/jquery/src/traversing/var/dir'>;
}
declare module 'iban/demo/bower_components/jquery/src/traversing/var/rneedsContext.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/jquery/src/traversing/var/rneedsContext'>;
}
declare module 'iban/demo/bower_components/jquery/src/traversing/var/siblings.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/jquery/src/traversing/var/siblings'>;
}
declare module 'iban/demo/bower_components/jquery/src/var/arr.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/jquery/src/var/arr'>;
}
declare module 'iban/demo/bower_components/jquery/src/var/class2type.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/jquery/src/var/class2type'>;
}
declare module 'iban/demo/bower_components/jquery/src/var/concat.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/jquery/src/var/concat'>;
}
declare module 'iban/demo/bower_components/jquery/src/var/document.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/jquery/src/var/document'>;
}
declare module 'iban/demo/bower_components/jquery/src/var/documentElement.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/jquery/src/var/documentElement'>;
}
declare module 'iban/demo/bower_components/jquery/src/var/fnToString.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/jquery/src/var/fnToString'>;
}
declare module 'iban/demo/bower_components/jquery/src/var/getProto.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/jquery/src/var/getProto'>;
}
declare module 'iban/demo/bower_components/jquery/src/var/hasOwn.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/jquery/src/var/hasOwn'>;
}
declare module 'iban/demo/bower_components/jquery/src/var/indexOf.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/jquery/src/var/indexOf'>;
}
declare module 'iban/demo/bower_components/jquery/src/var/ObjectFunctionString.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/jquery/src/var/ObjectFunctionString'>;
}
declare module 'iban/demo/bower_components/jquery/src/var/pnum.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/jquery/src/var/pnum'>;
}
declare module 'iban/demo/bower_components/jquery/src/var/push.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/jquery/src/var/push'>;
}
declare module 'iban/demo/bower_components/jquery/src/var/rcssNum.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/jquery/src/var/rcssNum'>;
}
declare module 'iban/demo/bower_components/jquery/src/var/rnothtmlwhite.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/jquery/src/var/rnothtmlwhite'>;
}
declare module 'iban/demo/bower_components/jquery/src/var/slice.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/jquery/src/var/slice'>;
}
declare module 'iban/demo/bower_components/jquery/src/var/support.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/jquery/src/var/support'>;
}
declare module 'iban/demo/bower_components/jquery/src/var/toString.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/jquery/src/var/toString'>;
}
declare module 'iban/demo/bower_components/jquery/src/wrap.js' {
  declare module.exports: $Exports<'iban/demo/bower_components/jquery/src/wrap'>;
}
declare module 'iban/demo/js/countries.js' {
  declare module.exports: $Exports<'iban/demo/js/countries'>;
}
declare module 'iban/demo/js/demo.js' {
  declare module.exports: $Exports<'iban/demo/js/demo'>;
}
declare module 'iban/demo/js/ie-emulation-modes-warning.js' {
  declare module.exports: $Exports<'iban/demo/js/ie-emulation-modes-warning'>;
}
declare module 'iban/demo/js/ie10-viewport-bug-workaround.js' {
  declare module.exports: $Exports<'iban/demo/js/ie10-viewport-bug-workaround'>;
}
declare module 'iban/iban.js' {
  declare module.exports: $Exports<'iban/iban'>;
}
declare module 'iban/test/ibanTest.js' {
  declare module.exports: $Exports<'iban/test/ibanTest'>;
}
