// flow-typed signature: 809c1d42cd452a4c5bddcd68d3df7754
// flow-typed version: <<STUB>>/redux-async-load_v^0.2.4/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-async-load'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-async-load' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-async-load/lib/action' {
  declare module.exports: any;
}

declare module 'redux-async-load/lib/Container' {
  declare module.exports: any;
}

declare module 'redux-async-load/lib/index' {
  declare module.exports: any;
}

declare module 'redux-async-load/lib/Loader' {
  declare module.exports: any;
}

declare module 'redux-async-load/lib/reducer' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-async-load/lib/action.js' {
  declare module.exports: $Exports<'redux-async-load/lib/action'>;
}
declare module 'redux-async-load/lib/Container.js' {
  declare module.exports: $Exports<'redux-async-load/lib/Container'>;
}
declare module 'redux-async-load/lib/index.js' {
  declare module.exports: $Exports<'redux-async-load/lib/index'>;
}
declare module 'redux-async-load/lib/Loader.js' {
  declare module.exports: $Exports<'redux-async-load/lib/Loader'>;
}
declare module 'redux-async-load/lib/reducer.js' {
  declare module.exports: $Exports<'redux-async-load/lib/reducer'>;
}
