// flow-typed signature: ffe0a5e61832cc85f824b260b81c902c
// flow-typed version: <<STUB>>/stylelint-bare-webpack-plugin_v^0.1.3/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stylelint-bare-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'stylelint-bare-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'stylelint-bare-webpack-plugin/stylelint-bare' {
  declare module.exports: any;
}

// Filename aliases
declare module 'stylelint-bare-webpack-plugin/stylelint-bare.js' {
  declare module.exports: $Exports<'stylelint-bare-webpack-plugin/stylelint-bare'>;
}
